### ISSUE TITLE
Text16 type probably doesn't make sense any more

### ISSUE THREAD

**Issue by ghost** [j-mie6/ParsleyHaskell#45]
With the move of the internal representation from utf-16 to utf-8 in v2.0, [`Text16`](https://hackage.haskell.org/package/parsley-core-2.0.0.0/docs/Parsley-Internal-Core-InputTypes.html#t:Text16) probably isn't a very useful abstraction (and really it's not a great idea to rely on the encoding of an opaque `Text` at all). Not sure what effects this will have or what assumptions will be broken by the change, but flagging it so it can be tracked.

**Comment by j-mie6** [comment]
Thanks for letting me know. There will be some changes required on my end to make things work nicely in the internals, but that's fine, I can use package versioning macros to arbitrate between versions. Text16 will be removed from the API for text >= 2, and deprecated for future removal. There's definitely no point in Text8, because at that point a ByteString would be an identical implementation.

**Comment by j-mie6** [comment]
Note that the `Text` backend itself is entirely unaffected by this change, it's only `Text16` that needs to be removed, no further changes.
